---
title: "Trip Purpose"
author: "Nate Lant"
date: "12/16/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(scales)
```

```{r persons.data}
# Creating variables and filtering the persons population
nhts_persons <- nhts_persons %>% 
  mutate(hhpersonid = paste(houseid, personid, sep = "-"), # Joins household ID with person ID so that each person has a unique ID
         Ability = case_when(w_chair == "07" | w_mtrchr == "08" ~ "Wheelchair",
                             medcond6 == "02" | medcond6 == "03" ~ "Disabled",  
                             medcond == "02" ~ "Abled"),
         Income = case_when(hhfaminc == "01" | hhfaminc == "02" | hhfaminc == "03" ~ "Low",
                            hhfaminc == "04" | hhfaminc == "05" ~ "Mid-Low",
                            hhfaminc == "06" | hhfaminc == "07" ~ "Mid-High",
                            hhfaminc == "08" | hhfaminc == "09" | hhfaminc == "10" | hhfaminc == "11" ~ "High"),
         Income = fct_relevel(Income, "Low", "Mid-Low", "Mid-High", "High")) %>% 
    filter(r_age >= 18 & r_age < 65,
           Ability != "NA",
           Income != "NA")
```

# How does travel differ between wheelchair users and the abled population considering trip purpose?

```{r trip.purpose, message=F, warning=F}
# This attempt contains all trips (all households, persons, etc.)
new_trips <- nhts_trips %>% mutate(hhpersonid = paste(houseid, personid, sep = "-")) %>%
  filter(hhpersonid %in% nhts_persons$hhpersonid) %>%
  group_by(hhpersonid, trippurp) %>%
  tally() %>%
  mutate(n = ifelse(n > 10, 10, n))


# builds the grid
new_grid <- expand_grid(hhpersonid = unique(new_trips$hhpersonid), trippurp = unique(new_trips$trippurp)) %>%
  filter(trippurp != "-9")


# combine the grid and the trips then pipe into a histogram
joined_grid_trips <- new_trips %>% right_join(new_grid) %>%
  mutate(n = ifelse(is.na(n), 0, n)) %>%
  left_join(nhts_persons, "hhpersonid") %>% 
  group_by(Ability)

  # pipe into the histogram
  ggplot(joined_grid_trips, aes(x = n)) + 
  geom_histogram(aes(y = stat(width*density), fill = Ability), binwidth = 0.8, colour = "black", size = .1, position = "dodge") +
    ggtitle("Comparing the number of trips by trip purpose and Income group", subtitle = "Comparison of Ability") +
    labs(x = "Number of Trips", y = "Percent of subgroup population") +
    scale_fill_brewer(palette = "PuBuGn", direction = 1) + 
    theme(axis.text.x = element_text(size  = 10, 
                                     angle = 45,
                                     hjust = 1,
                                     vjust = 1)) +
    scale_x_continuous(breaks = c(0:10)) +
    scale_y_continuous(labels = percent_format()) +
    facet_grid(Income ~ trippurp, scales = "free_x")
  
  #plot %>% ggplotly(tooltip = c("x", "y", "fill")) %>% layout(boxmode = "group")

```